#!/bin/bash
function usage() { 
		 [[ $# -eq 3 ]] \
                 || echo -e "your command $*\n "\
		            "useage: $0 <tidydir> <srcdir> <objdir>" \
		 && exit 1
 }
 
function ensuredir() { 
		 test -d $1 || mkdir $1
}

function moveFiles() { 
		 for f in $2/*$1 
		 do mv $f $3
		 done
}

usage $* || exit
test -d $1 || exit 
ensuredir $2 && moveFiles .c $1 $2 || exit 
ensuredir $3 && moveFiles .o $1 $3 || exit 

